import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { format } from "prettier";
import { z } from "zod";

const target = resolve(process.cwd(), "docs/agent-api.md");

type JsonSchema = {
  properties?: Record<string, { default?: unknown }>;
  required?: string[];
  anyOf?: JsonSchema[];
};

function objectSignature(schema: z.ZodType): string {
  const json = z.toJSONSchema(schema, {
    target: "draft-2020-12",
  }) as JsonSchema;
  const branches = json.anyOf ?? [json];
  return branches
    .map((branch) => {
      const required = new Set(branch.required ?? []);
      const fields = Object.entries(branch.properties ?? {}).map(([name, property]) => {
        const suffix = required.has(name)
          ? "*"
          : property.default !== undefined
            ? `=${JSON.stringify(property.default)}`
            : "?";
        return `${name}${suffix}`;
      });
      return `{ ${fields.join(", ")} }`;
    })
    .join(" or ");
}

type DocumentedTool = {
  name: string;
  domain: string;
  summary: string;
  useWhen: string;
  avoidWhen: string;
  returns: string;
  inputSchema: z.ZodType;
  outputSchema: z.ZodType;
  effects: { kind: string; destructive: boolean; retry: string; confirmation: string };
  exposure: string;
  replacedBy?: string;
};

function render(tools: DocumentedTool[], contractVersion: number): string {
  const domains = [...new Set(tools.map((tool) => tool.domain))];
  const sections = domains
    .map((domain) => {
      const entries = tools
        .filter((tool) => tool.domain === domain)
        .map(
          (tool) => `### \`${tool.name}\`

${tool.summary}

- Use when: ${tool.useWhen}
- Avoid when: ${tool.avoidWhen}
- Returns: ${tool.returns}
- Effects: ${tool.effects.kind}; destructive=${String(tool.effects.destructive)}; retry=${tool.effects.retry}; confirmation=${tool.effects.confirmation}
- Exposure: ${tool.exposure}${tool.replacedBy ? `; replaced by \`${tool.replacedBy}\`` : ""}
- Arguments: \`${objectSignature(tool.inputSchema)}\`
- Output: \`${objectSignature(tool.outputSchema)}\`

Call \`describe_tool\` for field descriptions, enums, nested objects, examples, and the
complete input/output JSON Schemas.`,
        )
        .join("\n\n");
      return `## ${domain[0].toUpperCase()}${domain.slice(1)}\n\n${entries}`;
    })
    .join("\n\n");

  return `<!-- Generated by npm run agent:docs. Do not edit by hand. -->
# Agent API

Contract version: **${contractVersion}**

Spec: \`agent-os/specs/2026-08-09-1130-agent-tool-contracts/\`
MCP transport: \`agent-os/specs/2026-08-13-1730-remote-mcp-transport/\`

Planner exposes focused HTTP tools so an external agent can read and update the planner.
The executable registry in \`src/lib/agent/tools.ts\` is canonical; this file is a generated
human-readable projection. Chat clients that speak MCP (Grok custom connectors, Claude)
use the same registry at \`POST /api/mcp\` instead of the per-tool HTTP routes.

## Setup

Set \`PLANNER_AGENT_API_KEY\` to a long random secret and
\`PLANNER_AGENT_USER_EMAIL\` to the account the key represents. Start Planner on port 3047,
then call:

\`\`\`http
POST /api/agent/{tool}
Authorization: Bearer <PLANNER_AGENT_API_KEY>
Content-Type: application/json

{ …arguments }
\`\`\`

Success is \`{ "ok": true, "data": … }\`. Failure is
\`{ "ok": false, "error": { "code", "message" } }\`.

Remote MCP (Streamable HTTP, JSON only) uses the same Bearer key:

\`\`\`http
POST /api/mcp
Authorization: Bearer <PLANNER_AGENT_API_KEY>
Content-Type: application/json
\`\`\`

\`tools/list\` exposes the current core and domain tools — not HTTP discovery
(\`list_tools\`, \`describe_tool\`, \`health\`) or legacy aliases. In Grok: grok.com/connectors
→ New Connector → Custom, name \`Planner\`, URL
\`https://planner-lee-5344.vercel.app/api/mcp\`, then paste the Bearer key.

## Discovery first

Call \`list_tools\` with no arguments for the ten-tool core surface. Request a domain only
when needed, then call \`describe_tool\` for the selected tool's current schemas and retry
contract. Legacy aliases are hidden unless \`includeLegacy\` is true.

\`\`\`sh
./scripts/call-tool.sh list_tools '{}'
./scripts/call-tool.sh list_tools '{"domain":"planning"}'
./scripts/call-tool.sh describe_tool '{"name":"update_weekly_plan_entries"}'
\`\`\`

All input objects are strict: unknown fields return a \`validation\` error. List/search
tools return paging metadata and never silently truncate. Creation tools that advertise
\`safe_with_external_ref\` require both \`externalSource\` and \`externalId\` for retry
safety; appointment writes deliberately advertise \`unsafe\` because calendar sync crosses
an external non-atomic boundary.

${sections}
`;
}

async function main(): Promise<void> {
  // Importing the registry also imports domain handlers, whose database client validates
  // this variable at module load. Documentation never connects; the placeholder keeps the
  // generator hermetic when no local environment file exists.
  process.env.DATABASE_URL ??= "postgres://unused:unused@localhost:5432/unused";
  process.env.BETTER_AUTH_URL ??= "http://localhost:3047";
  const { AGENT_CONTRACT_VERSION, TOOL_REGISTRY } =
    await import("../src/lib/agent/tools");
  const content = await format(
    render([...TOOL_REGISTRY.values()], AGENT_CONTRACT_VERSION),
    { parser: "markdown" },
  );
  if (process.argv.includes("--check")) {
    const current = await readFile(target, "utf8").catch(() => "");
    if (current !== content) {
      console.error("docs/agent-api.md is out of date; run npm run agent:docs");
      process.exitCode = 1;
    }
  } else {
    await writeFile(target, content);
  }
}

void main();
